// DIM_TEMPS 
let
    // =========================================================================
    // ÉTAPE 1: Extraire TOUTES les dates des commandes 
    // =========================================================================
    Dates_TempsExcel = Table.SelectColumns(#"Temps_Excel", {"Order Date"}),
    #"Renomme_TempsExcel" = Table.RenameColumns(Dates_TempsExcel, {{"Order Date", "DateComplete"}}),
    
    Dates_Orders = Table.SelectColumns(#"Orders", {"OrderDate"}),
    #"Renomme_Orders" = Table.RenameColumns(Dates_Orders, {{"OrderDate", "DateComplete"}}),
    
    // =========================================================================
    // ÉTAPE 2: Combiner TOUTES les dates 
    // =========================================================================
    ToutesDates = Table.Combine({#"Renomme_TempsExcel", #"Renomme_Orders"}),
    
    #"DatesFiltrees" = Table.SelectRows(ToutesDates, each [DateComplete] <> null and [DateComplete] <> ""),
    
    #"TypeDate" = Table.TransformColumnTypes(#"DatesFiltrees", {{"DateComplete", type date}}),
    
    // =========================================================================
    // ÉTAPE 3: Ajouter les colonnes calculées SUR CHAQUE LIGNE
    // =========================================================================
    #"AjouteAnnee" = Table.AddColumn(#"TypeDate", "annee", each Date.Year([DateComplete]), Int64.Type),
    
    #"AjouteMoisAnnee" = Table.AddColumn(#"AjouteAnnee", "mois_annee", each 
        Text.PadStart(Text.From(Date.Month([DateComplete])), 2, "0") & "/" & Text.From(Date.Year([DateComplete])), 
        type text
    ),
    
    // =========================================================================
    // ÉTAPE 4: Ajouter l'ID séquentiel 
    // =========================================================================
    #"AjouteIndex" = Table.AddIndexColumn(#"AjouteMoisAnnee", "id_temps", 1, 1, Int64.Type),
    
    // =========================================================================
    // ÉTAPE 5: SÉLECTIONNER SANS DATECOMPLETE
    // =========================================================================
    #"SansDateComplete" = Table.SelectColumns(#"AjouteIndex", {
        "id_temps",
        "annee", 
        "mois_annee"
    })
in
    #"SansDateComplete"