// TF_COMMANDE - VERSION 878 LIGNES EXACTES
let
    // =========================================================================
    // ÉTAPE 1: Préparer les données avec ID_TEMPS DIRECT
    // =========================================================================
    Orders_SSMS = Table.SelectColumns(#"Orders", {"OrderID", "CustomerID", "EmployeeID", "OrderDate", "ShippedDate"}),
    #"SSMS_WithFlags" = Table.AddColumn(Orders_SSMS, "nbr_commande_livrees", each if [ShippedDate] <> null then 1 else 0),
    #"SSMS_WithFlags2" = Table.AddColumn(#"SSMS_WithFlags", "nbr_commande_non_livrees", each if [ShippedDate] = null then 1 else 0),
    #"SSMS_WithSource" = Table.AddColumn(#"SSMS_WithFlags2", "source_prod", each "SSMS"),

    Orders_Excel_Prepared = Table.SelectColumns(#"Orders_Excel", {"Order ID", "Customer ID", "Employee ID", "Order Date", "Shipped Date"}),
    #"Excel_WithFlags" = Table.AddColumn(Orders_Excel_Prepared, "nbr_commande_livrees", each if [Shipped Date] <> null then 1 else 0),
    #"Excel_WithFlags2" = Table.AddColumn(#"Excel_WithFlags", "nbr_commande_non_livrees", each if [Shipped Date] = null then 1 else 0),
    #"Excel_WithSource" = Table.AddColumn(#"Excel_WithFlags2", "source_prod", each "EXCEL"),

    // Standardiser les noms
    SSMS_Standardized = Table.RenameColumns(#"SSMS_WithSource", {
        {"OrderID", "OrderID"}, {"CustomerID", "CustomerID"}, {"EmployeeID", "EmployeeID"},
        {"OrderDate", "OrderDate"}, {"ShippedDate", "ShippedDate"}
    }),

    Excel_Standardized = Table.RenameColumns(#"Excel_WithSource", {
        {"Order ID", "OrderID"}, {"Customer ID", "CustomerID"}, {"Employee ID", "EmployeeID"},
        {"Order Date", "OrderDate"}, {"Shipped Date", "ShippedDate"}
    }),

    CombinedData = Table.Combine({SSMS_Standardized, Excel_Standardized}),
    
    // =========================================================================
    // ÉTAPE 2: AJOUTER ID_TEMPS DIRECTEMENT (878 LIGNES)
    // =========================================================================
    #"TypeCorrige" = Table.TransformColumnTypes(CombinedData, {
        {"CustomerID", type text}, {"EmployeeID", type text}, {"OrderID", type text},
        {"OrderDate", type date}
    }),

    // AJOUTER ID_TEMPS SÉQUENTIEL DIRECTEMENT (1 par commande)
    #"AjouteIdTemps" = Table.AddIndexColumn(#"TypeCorrige", "id_temps", 1, 1, Int64.Type),

    // =========================================================================
    // ÉTAPE 3: JOINTURES AVEC DIM_CLIENT ET DIM_EMPLOYEE
    // =========================================================================
    // Jointure Dim_Client
    #"JoinDimClient" = Table.NestedJoin(
        #"AjouteIdTemps", 
        {"CustomerID", "source_prod"}, 
        #"DimClient", 
        {"id_client_prod", "source_prod"}, 
        "ClientData", 
        JoinKind.LeftOuter
    ),
    #"ExpandedClient" = Table.ExpandTableColumn(#"JoinDimClient", "ClientData", {"id_seqClient"}, {"id_seqClient"}),

    // Jointure Dim_Employee (version unique)
    Dim_Employee_Unique = Table.Group(#"Dim_Employee", 
        {"id_employee_prod", "source_prod"}, {
            {"id_seqEmployee", each List.Min([id_seqEmployee]), Int64.Type}
        }
    ),
    
    #"JoinDimEmployee" = Table.NestedJoin(
        #"ExpandedClient", 
        {"EmployeeID", "source_prod"}, 
        Dim_Employee_Unique, 
        {"id_employee_prod", "source_prod"}, 
        "EmployeeData", 
        JoinKind.LeftOuter
    ),
    #"ExpandedEmployee" = Table.ExpandTableColumn(#"JoinDimEmployee", "EmployeeData", {"id_seqEmployee"}, {"id_seqEmployee"}),

    // =========================================================================
    // ÉTAPE 4: AGRÉGATION PAR COMMANDE (878 LIGNES)
    // =========================================================================
    #"AgregeParCommande" = Table.Group(#"ExpandedEmployee", 
        {"OrderID", "id_temps", "id_seqEmployee", "id_seqClient", "source_prod"}, {
            {"nbr_commande_livrees", each List.Sum([nbr_commande_livrees]), type number},
            {"nbr_commande_non_livrees", each List.Sum([nbr_commande_non_livrees]), type number}
        }
    ),

    // =========================================================================
    // ÉTAPE 5: NETTOYAGE FINAL
    // =========================================================================
    #"ColonnesNettoyees" = Table.RemoveColumns(#"AgregeParCommande", {
        "OrderID", "source_prod"
    }),

    #"AddedIndex" = Table.AddIndexColumn(#"ColonnesNettoyees", "id_seq_fait", 1, 1, Int64.Type),

    #"FinalColumns" = Table.SelectColumns(#"AddedIndex", {
        "id_seq_fait", "id_temps", "id_seqEmployee", "id_seqClient", 
        "nbr_commande_livrees", "nbr_commande_non_livrees"
    })
in
    #"FinalColumns"